package main.java.com.luist23.mef3d.scenes.numeracion;

public enum TypeScene {
    MAIN, STAGE2 , BIENVENIDA,MODELO,DOMINIO,CONDICIONES,
    MALLA,TABLA,PASO1,PASO2,PASO3,PASO4,PASO5,PASO6,MATRICES,ENSAMBLAJE,PASO8,DESPEDIDA,
    S3D,NONE
}